apiVersion: apps/v1
kind: Deployment
metadata:
  name: spire-server
  namespace: spire
  labels:
    app: spire-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spire-server
  template:
    metadata:
      namespace: spire
      labels:
        app: spire-server
    spec:
      serviceAccountName: spire-server
      shareProcessNamespace: true
      initContainers:
        - name: plugin-loader
          image: 074122282848.dkr.ecr.us-east-1.amazonaws.com/spire-aws-auth-plugin:v0.1.0
          imagePullPolicy: Always
          command: ["/bin/cp", "/bin/spire-aws-auth-plugin", "/spire/custom-plugins/spire-aws-auth-plugin"]
          volumeMounts:
            - name: custom-plugin-dir
              mountPath: /spire/custom-plugins
      containers:
        - name: spire-server
          image: ghcr.io/spiffe/spire-server:1.11.0
          args: ["-config", "/run/spire/server/config/server.conf"]
          ports:
            - containerPort: 8081
          env:
            - name: AWS_REGION
              value: "us-east-1"
          volumeMounts:
            - name: spire-config
              mountPath: /run/spire/server/config
              readOnly: true
            - name: vault-certs
              mountPath: /run/spire/vault-certs
              readOnly: true
            - name: spire-data
              mountPath: /run/spire/data
              readOnly: false
            - name: spire-server-socket
              mountPath: /tmp/spire-server/private
              readOnly: false
            - name: custom-plugin-dir
              mountPath: /opt/spire/plugins/custom
              readOnly: true
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 100
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 100
            successThreshold: 1
        - name: spire-controller-manager
          image: docker.io/fengyu225/spire-controller-manager:latest
          imagePullPolicy: Always
          args: ["--config=spire-controller-manager-config.yaml"]
          ports:
            - containerPort: 9443
          volumeMounts:
            - name: spire-server-socket
              mountPath: /spire-server
              readOnly: true
            - name: spire-controller-manager-config
              mountPath: /spire-controller-manager-config.yaml
              subPath: spire-controller-manager-config.yaml
      volumes:
        - name: spire-config
          configMap:
            name: spire-server
        - name: vault-certs
          secret:
            secretName: vault-certs
        - name: spire-server-socket
          emptyDir: {}
        - name: spire-data
          emptyDir: {}
        - name: spire-controller-manager-config
          configMap:
            name: spire-controller-manager-config
        - name: custom-plugin-dir
          emptyDir: {}