apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-init
  namespace: spire
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-init-role
  namespace: spire
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "patch", "delete", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-init-binding
  namespace: spire
subjects:
  - kind: ServiceAccount
    name: vault-init
    namespace: spire
roleRef:
  kind: Role
  name: vault-init-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: spire
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:1.15
          args: ["server", "-dev", "-dev-tls", "-dev-root-token-id=root", "-dev-listen-address=0.0.0.0:8200"]
          env:
            - name: VAULT_ADDR
              value: "https://127.0.0.1:8200"
            - name: VAULT_SKIP_VERIFY
              value: "true"
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
          ports:
            - containerPort: 8200
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "VAULT_ADDR=https://127.0.0.1:8200 vault status -tls-skip-verify"]
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: spire
spec:
  ports:
    - port: 8200
      targetPort: 8200
  selector:
    app: vault
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-init-script
  namespace: spire
data:
  init.sh: |
    #!/bin/sh
    set -e
    
    apk add --no-cache openssl curl

    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    mv kubectl /usr/local/bin/

    export VAULT_ADDR='https://vault:8200'
    export VAULT_TOKEN='root'
    export VAULT_SKIP_VERIFY='true'

    echo "Waiting for Vault..."
    until vault status -tls-skip-verify > /dev/null 2>&1; do
      sleep 2
    done

    echo "Vault is up. Configuring PKI..."

    vault secrets enable -tls-skip-verify -path=pki_root pki || true
    vault secrets tune -tls-skip-verify -max-lease-ttl=87600h pki_root

    vault write -tls-skip-verify pki_root/root/generate/internal \
        common_name="SPIRE Root CA" \
        ttl=87600h \
        key_type="ec" \
        key_bits=384 \
        issuer_name="spire-root-2025"

    vault write -tls-skip-verify pki_root/config/urls \
        issuing_certificates="$VAULT_ADDR/v1/pki_root/ca" \
        crl_distribution_points="$VAULT_ADDR/v1/pki_root/crl"

    vault auth enable -tls-skip-verify cert || true
    vault auth tune -tls-skip-verify -max-lease-ttl=87600h cert

    echo "Generating Client Certs..."
    mkdir -p certs
    
    openssl genrsa -out certs/client.key 4096
    openssl req -new -key certs/client.key -out certs/client.csr \
        -subj "/CN=spire-server/O=SPIRE"
    
    openssl x509 -req -in certs/client.csr \
        -signkey certs/client.key \
        -out certs/client.crt \
        -days 3650 -sha256

    vault policy write -tls-skip-verify spire-server-policy - <<EOF
    path "pki_root/root/sign-intermediate" { capabilities = ["create", "update"] }
    path "pki_root/cert/ca" { capabilities = ["read"] }
    path "pki_root/crl" { capabilities = ["read"] }
    path "auth/cert/login" { capabilities = ["create", "read"] }
    path "pki_root/config/*" { capabilities = ["read"] }
    path "pki_root/roles/*" { capabilities = ["create", "read", "update"] }
    path "pki_root/issue/*" { capabilities = ["create", "update"] }
    EOF

    vault write -tls-skip-verify auth/cert/certs/spire-server \
        display_name="spire-server" \
        policies="spire-server-policy" \
        certificate=@certs/client.crt \
        ttl=87600h \
        allowed_common_names="spire-server" \
        allowed_organizations="SPIRE" \
        require_matching_certificates=true

    vault read -tls-skip-verify -field=certificate pki_root/cert/ca > certs/ca.crt

    echo "Creating Kubernetes Secret..."
    kubectl create secret generic vault-certs \
      --from-file=ca.crt=certs/ca.crt \
      --from-file=client.crt=certs/client.crt \
      --from-file=client.key=certs/client.key \
      -n spire --dry-run=client -o yaml | kubectl apply -f -

    echo "Vault Initialization Complete!"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init-job
  namespace: spire
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      serviceAccountName: vault-init
      restartPolicy: OnFailure
      containers:
        - name: init
          image: hashicorp/vault:1.15
          command: ["/bin/sh", "/scripts/init.sh"]
          volumeMounts:
            - name: script-vol
              mountPath: /scripts
      volumes:
        - name: script-vol
          configMap:
            name: vault-init-script
            defaultMode: 0755